services:
  # api:
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./app:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./frontend:/app
