services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - fitty
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 6969:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fitty
  proxy:
    build: ./proxy
    ports: ['7778:80']
    networks:
      - fitty

networks:
  fitty:
    driver: bridge

volumes:
  node_modules: